export const SET_CERTIFICATES: 'SET_CERTIFICATES' = 'SET_CERTIFICATES';
export const SET_SELECT_CERTIFICATE: 'SET_SELECT_CERTIFICATE' =
  'SET_SELECT_CERTIFICATE';
export const SET_CERTIFICATE_NUMBER: 'SET_CERTIFICATE_NUMBER' =
  'SET_CERTIFICATE_NUMBER';
