export const SET_CERTIFICATES: 'SET_CERTIFICATES' = 'SET_CERTIFICATES';
export const SET_SELECT_CERTIFICATE: 'SET_SELECT_CERTIFICATE' =
  'SET_SELECT_CERTIFICATE';
export const SET_CERTIFICATE_NUMBER: 'SET_CERTIFICATE_NUMBER' =
  'SET_CERTIFICATE_NUMBER';
export const SET_REQUEST: 'SET_REQUEST' = 'SET_REQUEST';
export const SET_SUCCESS: 'SET_SUCCESS' = 'SET_SUCCESS';
export const SET_FAILED: 'SET_FAILED' = 'SET_FAILED';
